### ISSUE TITLE
[Feature Request] Jellyfin Support

### ISSUE THREAD

**Issue by CrazyWolf13** [keifufu/WebNowPlaying-Redux#10]
Is it possible to add Jellyfin support? 
It's basically a self hosted media center software like Plex.
(The ip of the webpage will be different on every user)

**Comment by CrazyWolf13** [comment]
> Sure, I can easily support the music player (the bar at the bottom), but videos are going to have some issues:
> - No thumbnails
> - No support for repeat/shuffle states

That's great, thank you a lot.
Maybe in the video you could use the initial image that is loaded on the main jellyfin page but i'm not sure how this is implemented.

**Comment by keifufu** [comment]
That's not a bad idea, I'll try that, no guarantee though.

Probably going to release a new update including support for jellyfin some time tomorrow.

**Comment by CrazyWolf13** [comment]
> That's not a bad idea, I'll try that, no guarantee though.
> 
> Probably going to release a new update including support for jellyfin some time tomorrow.

Hey, sorry for coming back so late, i had still the manually installed version so the extension did not update automatically, lmao silly me.

Could you get some thing like the cover image to work with jellyfin?
Or would it be possible to at least display the media player's logo if there is no cover?

**Comment by keifufu** [comment]
Please try again with recent commits. Should work for all videos now.

**Comment by CrazyWolf13** [comment]
Thank you!

keifufu ***@***.***> schrieb am Sa., 15. Apr. 2023, 10:14:
