### ISSUE TITLE
how can i make it work with yt music desktop

### ISSUE THREAD

**Issue by Stromy08** [keifufu/WebNowPlaying-Redux#13]
![image](https://github.com/keifufu/WebNowPlaying-Redux/assets/125371422/2a962b88-e172-4880-8750-ef97ff1243ad)
i made it work with browser youtube but this doesnt work and it does have a setting ot do it so im not sure how ot do it

**Comment by keifufu** [comment]
This app doesn't work with webnowplaying anymore. You can try updating the Rainmeter plugin and making use of [Native APIs](https://github.com/keifufu/WebNowPlaying-Redux/blob/main/NativeAPIs.md).
This will only work if the app reports media info to Windows though, if it doesn't I recommend asking the developers to implement it.
