### ISSUE TITLE
not sure is that extension issue but right text but wrong picture

### ISSUE THREAD

**Issue by Makezu90** [keifufu/WebNowPlaying-Redux#15]
But it shows wrong picture. I tried reinstall rainmeter skin, not helped, uninstall this webnowplaying - not helped. I think that happened yesterday. Also not helped it shows also same picture if i try watch some youtube video, however that text is correct. 

Now i watching:

![opera_39FqAkzQhx](https://github.com/keifufu/WebNowPlaying-Redux/assets/89158176/6d19105e-81b7-472e-a5c5-bac3f3876be5)

what skin looks now:

![BhbV0yumLJ](https://github.com/keifufu/WebNowPlaying-Redux/assets/89158176/cd01f0bc-d9b6-4697-a543-161a3aff0921)

also discord (i use Premid):

![Discord_D45ACMeYhi](https://github.com/keifufu/WebNowPlaying-Redux/assets/89158176/48b1aeb1-e337-4042-9ae4-fda80434613d)

**Comment by Makezu90** [comment]
update: when i install old webnowplaying skin what i found i have -> WebNowPlaying_0.5.0.rmskin it say not recommended but i can install it normally but then extension say there is update and when i update that issue appears?

**Comment by keifufu** [comment]
It is totally stuck even if you play something on YouTube, etc. or only with twitch?
In general, just try restarting Rainmeter, your browser or your computer.

**Comment by XisUndefined** [comment]
what skin do you use that shows the wrong picture?

**Comment by Makezu90** [comment]
> what skin do you use that shows the wrong picture?

I use this: https://www.deviantart.com/xenium-art/art/Black-Panther-Suite-UPDATED-19-MAY-2023-911894723

It happens atleast youtube and twitch. I tried all things restart pc.. Rainmeter. When i install old plugin there is no any issues but when i update it newest issue appears

**Comment by keifufu** [comment]
Make sure you are using WebNowPlaying 2.0.0 or 2.0.1 as they have fixed some issues with downloading cover images from 1.2.0 which is bundled with the skin you use.

Otherwise, please try looking for the `PlayerType=Cover` Measure in the skin and removing the line starting with `CoverPath=` if it exists.

**Comment by Makezu90** [comment]
i tried that still same issue. and right now im using newest one. issue happens. i need to try find older which worked fine.

**Comment by keifufu** [comment]
While using an older version isn't a good solution, there's nothing preventing you from using it if it works for you.

Could you try going to `%LocalAppData%\Temp\Raimmeter\WebNowPlaying` and see if the image file in there updates correctly?

**Comment by Makezu90** [comment]
> 

v.1.2.0 yes.

v. 2.0.1 no.

**Comment by keifufu** [comment]
Really odd, any errors from webnowplaying in the rainmeter log?

**Comment by Makezu90** [comment]
> 

yes. it says so many errors and that: ImageName unable open in that place %LocalAppData%\Temp\Raimmeter\WebNowPlaying cover.png

**Comment by keifufu** [comment]
So again, does this only happen with Twitch or with every website?

**Comment by Makezu90** [comment]
> So again, does this only happen with Twitch or with every website?

not sure any other websites but atleast youtube and twitch.

**Comment by keifufu** [comment]
Is your browser extension updated? It says the version at the bottom right of the settings panel, should be either 2.0.0 or 2.0.1

**Comment by Makezu90** [comment]
yes its updated latest version 2.0.1

**Comment by keifufu** [comment]
The "ImageName unable open.." error isn't related to webnowplaying but rainmeter itself, please look for logs starting with "WebNowPlaying.dll - ..."

**Comment by Makezu90** [comment]
> 

weird. i cant see anything like errors with webnowplaying.dll  but that issue appears when i update plugin 2.0.0 -> skin works fine with v.1.2.0 and its shows right cover also when watching some from twitch. probably some skin issue then idk.

**Comment by keifufu** [comment]
You can test if it's a skin issue by using the bundled example skin, that skin should always work.

**Comment by Makezu90** [comment]
> You can test if it's a skin issue by using the bundled example skin, that skin should always work.

tried another skin -> https://www.deviantart.com/eclectic-tech/art/Lyrical-955447334 and i have newest version using also same thing. so its something rainmeter probably. whatever. if some older version works i will use that.

**Comment by keifufu** [comment]
This is certainly a WebNowPlaying issue but I am out of ideas as to what it could be, you seem to be the only person so far running into this issue..

**Comment by Makezu90** [comment]
> This is certainly a WebNowPlaying issue but I am out of ideas as to what it could be, you seem to be the only person so far running into this issue..

i can confirm, it wasn't. i think.. I did another account and tried only same skin and newest webnowplaying version no any issues. now i decided uninstall completely rainmeter so can't figure what it cause that. i noticed there was so many webnowplaying.dll version folders so i  removed other ones and only leave newest but it did not work.  not sure. i now install skins back i will let you know if this happens again.

**Comment by keifufu** [comment]
Interesting.
The many webnowplaying folders in @Vault are fine, the actual plugin is in %AppData%\Rainmeter\Plugins.
Just curious, what browser do you use?

**Comment by Makezu90** [comment]
opera gx, but also use it my other accoun too. 🤔

**Comment by keifufu** [comment]
You could try disabling native apis in the extensions settings panel and see if that was interfering with anything

**Comment by Makezu90** [comment]
now i try install only this skin should install webnowplaying.dll with this skin and then update or install newest webnowplaying and then add this skin?

**Comment by keifufu** [comment]
the order doesn't matter.

**Comment by Makezu90** [comment]
most likely i found what can cause that, it is using YourFlayout (jax core rainmeter skin). however skin what using it works, but browser extension say there is update oh well.. need to find alternative that flayout thing. and when install that jax core skin (your flayout) it install some very old plugin..

![Rainmeter_EUzUJg17Hq](https://github.com/keifufu/WebNowPlaying-Redux/assets/89158176/35759cb0-959e-406d-89a1-8adc46a3551a)

**Comment by keifufu** [comment]
Since I assume this is not a WebNowPlaying issue now, is it fair to close this issue?

**Comment by Makezu90** [comment]
> Since I assume this is not a WebNowPlaying issue now, is it fair to close this issue?

most likely no, but im not 100% sure, atleast it is fixed now.

**Comment by keifufu** [comment]
@Makezu90
I have found an issue where it doesn't save the cover for certain outdated skins.
Could you please try [v2.0.3](https://github.com/keifufu/WebNowPlaying-Redux-Rainmeter/releases/tag/2.0.3) and report back? Thank you!

**Comment by Makezu90** [comment]
> @Makezu90 I have found an issue where it doesn't save the cover for certain outdated skins. Could you please try [v2.0.3](https://github.com/keifufu/WebNowPlaying-Redux-Rainmeter/releases/tag/2.0.3) and report back? Thank you!

I can confirm that version fixed  this issue. thank you! :)

**Comment by keifufu** [comment]
:D
