### ISSUE TITLE
Rainmeter adapter on Google Chrome still reconecting

### ISSUE THREAD

**Issue by sudigra** [keifufu/WebNowPlaying-Redux#16]
![rain](https://github.com/keifufu/WebNowPlaying-Redux/assets/135423288/e3d3d4db-63e5-4585-b43d-4a55aa68fc51)
Why with my computer,
a few months ago, the application was running fine, for some reason this week I can't use it.
Please help,
1. Allow Firewall already
2. Reinstall Rainmeter already
3. Reinstall the Extension already

an error like this appears in the extension:
WebSocket connection to 'ws://localhost:8974/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

**Comment by keifufu** [comment]
It's being dumb sometimes, toggle the checkbox off and turn it back on after a few minutes.

If that doesn't fix it, make sure you have a rainmetr skin loaded that uses WebNowPlaying, just having it installed but unused doesn't work.

**Comment by keifufu** [comment]
Assuming this isn't a recurring issue and was just websocket fuckery
