### ISSUE TITLE
(YouTube only) WebNowPlaying Redux not working properly with DeArrow

### ISSUE THREAD

**Issue by jbcarreon123** [keifufu/WebNowPlaying-Redux#19]
## Synopsis 
When DeArrow changes the title of the video, WebNowPlaying Redux stops communicating the progress, but it changes the title correctly.

## Steps of reproduction
1. Install DeArrow
2. Watch a YouTube video that DeArrow changed it's title (you can see it by hovering on the video title, and seeing a blue blob on right side of the title)
3. See that it stops updating the progress bars, and it shows 0:00 on both the duration and the position
4. Reconnect the adapter
5. WebNowPlaying Redux shows the normal title, and the progress is working as it should be.

## Screenshots
![image](https://github.com/keifufu/WebNowPlaying-Redux/assets/86447165/2b0f5c56-b531-4153-bd17-ff386de007c5)
![image](https://github.com/keifufu/WebNowPlaying-Redux/assets/86447165/d1e5a468-ced9-43e7-b35a-759b27bf109f)

**Comment by keifufu** [comment]
I cannot replicate any of this. I also can't get it to report the changed title at all.

**Comment by jbcarreon123** [comment]
> I cannot replicate any of this. I also can't get it to report the changed title at all. Make sure your extension is updated (v2.0.7)

2.0.7 fixed it. Thanks!

**Comment by keifufu** [comment]
Can you confirm it only reports the original title? Would you like it to report the modified one?

**Comment by jbcarreon123** [comment]
> Can you confirm it only reports the original title? Would you like it to report the modified one?

That would be nice. I wouldn't force you to do it, but if you want to, go ahead.
