### ISSUE TITLE
Request: Add OneUI Widgets Adapter

### ISSUE THREAD

**Issue by Vaneeyo** [keifufu/WebNowPlaying-Redux#23]
Name: OneUI Widgets Adapter
GitHub: https://github.com/project-oneui/oneui-desktop-widgets
Description: Hey, I'm working on a windows project which creates desktop widgets in the OneUI Style. The OneUI Style is the newest design style of Samsung. And as I try to make the long configuration easier I would really appreciate if you could add the adapter. The port used for it is 8943.

**Comment by keifufu** [comment]
Looking at the source, I don't see anything to interface with WebNowPlaying or anything listening on port 8943. Perhaps I'm missing something?
Also, your description recommends installing [WebNowPlaying-Redux-Spicetify(https://github.com/keifufu/WebNowPlaying-Redux-Spicetify) which is no longer maintained as my adapters read data from desktop players via a Windows API.

**Comment by Vaneeyo** [comment]
Im really sorry, I added the false repository. Here is the right one: https://github.com/project-oneui/oneui-desktop-widgets-service. I didnt know the spicetify plugin isnt maintained anymore gonna look into it

**Comment by keifufu** [comment]
I see, the C# library doesn't have support for desktop players built-in. See more [here](https://wnp.keifufu.dev/creating-adapters/getting-started#c).

**Comment by Vaneeyo** [comment]
The best would be to use NodeJS, as the main app is based on it, but I myself dont know anything besides C# and JS. + If I use a compatible library I wont need the Spicetify plugin if I understand correct?

**Comment by Vaneeyo** [comment]
It also seems like the Spicetify Plugin doesnt work for the most part. Out of the CoverURL, Title, Artist, Length, Duration: I can only use the Duration

**Comment by keifufu** [comment]
You're making me want to create a js library now, xD.
Currently I got a C# and a Python library.
The python library has support for desktop players built-in on Windows.
The C# library doesn't as I had trouble building it when using Windows APIs in it, so the [Rainmeter adapter](https://github.com/keifufu/WebNowPlaying-Redux-Rainmeter) has the source of the C# library copied and extends it with [this implementation](https://github.com/keifufu/WebNowPlaying-Redux-Rainmeter/blob/main/src/WNPReduxAdapterLibraryExtensions/WNPReduxNative.cs).

All this does is read metadata from Windows using the [GSMTC API](https://learn.microsoft.com/en-us/uwp/api/windows.media.systemmediatransportcontrols?view=winrt-22621), which popular/modern players (Spotify Desktop included) report basic metadata such as Title, Artist, Duration, etc. to.

> It also seems like the Spicetify Plugin doesnt work for the most part. Out of the CoverURL, Title, Artist, Length, Duration: I can only use the Duration

This makes sense as the Spicetify implementations are only compatible with older versions of the library using older communication protocols.

**Comment by Vaneeyo** [comment]
My first approach was this API. My big problem was that spotify adds "Spotify" as text on the bottom but it seems like you fixed this by cropping it. So I think I will try to replicate your code for my circumstances. Thanks for the help

**Comment by keifufu** [comment]
Let me know if you need any help. Good luck!

**Comment by keifufu** [comment]
Also, does this mean you want to only use GSMTC or WNP+GSMTC? If the first then i can close this issue.

**Comment by Vaneeyo** [comment]
Im gonna use GSMTC, because using the browser isnt really what I want for the users. So GSMTC is better for users.
