### ISSUE TITLE
BandCamp not working as intended

### ISSUE THREAD

**Issue by PierG97** [keifufu/WebNowPlaying-Redux#3]
If I play a song from the album page, I can control the single song (pause, play, back to the beginning) but the commands to work with the entire album (next song, shuffle, repeat, etc...) don't work.

Additionally, if I play an album from My Collection, the extension doesn't work at all.

**Comment by keifufu** [comment]
I can't find buttons for repeat/shuffle, but I believe i managed to fix the rest.
I'm updating the extension on the webstores later today, might take a while for them to be verified.

**Comment by keifufu** [comment]
Seems like the extensions are already validated.
Closing this as I believe Bandcamp fully works now, but feel free to reply in case I missed something.

**Comment by PierG97** [comment]
First of all, thanks a lot of the quick reply and fix. I've tested it and yes, now it's fixed and I can control the songs while in the album page.

Unfortunately the extension doesn't work on the My Collection page. I've uploaded a recording where I show which page I'm talking about: [LINK](https://streamable.com/xqv1re)

The first half of the recording is the album page, which is the one that's been fixed (I recorded it to show that I've updated the extension correctly). In the second half of the recording, at 0:24, I show the My Collection page, where all the purchased albums are collected. As I've shown in the recording, the user can click on the album image to play it, and the buttons to control the songs appear on the bottom of the page. WNP-Redux doesn't recognize these buttons.

**Comment by keifufu** [comment]
I'm testing this on the wishlist tab actually, I assumed the player to be identical to the collections tab. Could you confirm that it works on the wishlist tab but not on the collection tab?
If so, is there a way to add music to the collection tab without buying it, so I can try to fix this?

**Comment by PierG97** [comment]
The player on the wishlist tab is the same, but iirc it only plays one sample music.

You could "buy" a free album ([random LINK](https://alightinthedark.bandcamp.com/album/a-long-journey-home)). It'll appear in your collection.

**Comment by keifufu** [comment]
Sure, my profile is keifufu

**Comment by PierG97** [comment]
Thank you!

Since I don't know your mail, to gift you an item I need you to wishlist an album.
1) [HERE](https://sequesteredkeep.bandcamp.com/album/wandering-far) is a random album. Click on the little heart icon below the album cover to wishlist it.
2) Make sure that your wishlist is not private. From the wishlist page, there should be a curtain menu on the right "Your wishlist is public/private".

I'm sorry to be such a bother for this. Unfortunately, this is the only way to gift an item to someone's bandcamp account if you don't know their mail.

**Comment by keifufu** [comment]
Added it to my wishlist!

**Comment by PierG97** [comment]
I've sent you the album as gift. I'm not sure how it works exactly, but you should receive a confirmation email.

**Comment by keifufu** [comment]
Yup, saw it! Thanks a lot.
I'm currently halfway through changing the way the rainmeter plugin communicates with the extension, so updating it might take a few days as I don't want to risk messing anything up.

**Comment by PierG97** [comment]
No problem, take your time. Thanks again for all the work you're doing!

**Comment by keifufu** [comment]
I'm sorry this is taking so long, it's been fixed by now but I'm pushing a lot, and I mean... a LOT of other changes into the extension before making a new release (as you can see by the git history).
I'm very close to being done and you can expect a new release the coming days.
Please note that the next release will replace the old WebNowPlaying Companion extension listings, after which the current listings will be deleted.
I'll close this issue once the extension is actually released, just thought I'd give you an update.

**Comment by PierG97** [comment]
Thanks for taking the time to give me an update, I really appreciate it! Don't worry about taking too long, I'm really grateful for the time you're spending on this :)

**Comment by keifufu** [comment]
It's up on the webstores now :)
I do remember you were talking about repeat and shuffle buttons which I don't think I was able to find but lmk if I was blind.
